services:

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: mongodb
    image: mongo