apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: devops-project
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ghcr.io/anja213158/devops-project:main
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: node-app-config 
                  key: NODE_ENV 
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: node-app-config
                  key: API_URL
